import json
import os
import pytest
from tests.tolerances import BPM_TOLERANCE, BEAT_TIMESTAMP_TOLERANCE

def floats_close(a, b, tol):
    return abs(a - b) <= tol

def test_golden_regression():
    # Compare output to golden file
    golden_path = os.path.join(os.path.dirname(__file__), "example_output.json")
    output_path = os.path.join(os.path.dirname(__file__), "example_output.json")
    # In real test, output_path would be generated by analyzer
    with open(golden_path) as f:
        golden = json.load(f)
    with open(output_path) as f:
        output = json.load(f)
    assert floats_close(golden["tempo"]["bpm"], output["tempo"]["bpm"], BPM_TOLERANCE)
    for gb, ob in zip(golden["rhythm"]["beats"], output["rhythm"]["beats"]):
        assert floats_close(gb, ob, BEAT_TIMESTAMP_TOLERANCE)
