# Tolerances for BeatSync Core tests
BPM_TOLERANCE = 0.5
BEAT_TIMESTAMP_TOLERANCE = 0.02  # 20 ms
BAR_TIMESTAMP_TOLERANCE = 0.05   # 50 ms
ENERGY_CURVE_MAE = 0.05
PEAK_ALIGNMENT_TOLERANCE = 0.1   # 100 ms
